site_name: RXMesh
site_url: https://mydomain.org/mysite
repo_url: https://github.com/owensgroup/RXMesh
repo_name: RXMesh
theme:  
  icon:
    repo: fontawesome/brands/github
  palette:     
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: light green
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: light green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.code.copy    
    - navigation.expand
    - navigation.indexes    
    #- navigation.tabs

nav:
  - About: 
    - about/compilation.md
    - about/dependencies.md
    - about/license.md
    - about/bibtex.md
  - Basics:
    - basics/basic.md
  - RXMesh: 
    - rxmesh/static.md
    - rxmesh/matrices.md
    - rxmesh/dynamic.md

