site_name: RXMesh
site_url: https://mydomain.org/mysite
repo_url: https://github.com/owensgroup/RXMesh
repo_name: RXMesh
theme:  
  icon:
    repo: fontawesome/brands/github
  palette:     
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light green
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: light green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode  

  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.code.copy    
    - navigation.expand
    - navigation.indexes    
    #- navigation.tabs

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - About: 
    - Building: about/building.md        
    - Bibtex: about/bibtex.md
  - Basics:
    - Getting Started: basics/basic.md
  - RXMesh: 
    - RXMeshStatic: rxmesh/static.md
    - Matrices: rxmesh/matrices.md
    - RXMeshDynamic: rxmesh/dynamic.md
    - Autodiff: rxmesh/ad.md
    - Applications: rxmesh/apps.md

