site_name: RXMesh
site_url: https://mydomain.org/mysite
repo_url: https://github.com/owensgroup/RXMesh
repo_name: RXMesh
theme:  
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: white
    accent: light green    
    

  name: material
  features:
    - navigation.sections    
    - toc.integrate
    - navigation.top
    - content.code.copy    
    - navigation.expand
    - navigation.indexes    
    - content.tabs.link
    #- navigation.tabs

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - About: 
    - Building: about/building.md        
    - Bibtex: about/bibtex.md
  - Basics:
    - Getting Started: basics/basic.md
  - User's Guide: 
    - RXMeshStatic: rxmesh/static.md      
    - Attributes: rxmesh/attribues.md
    - Matrices: rxmesh/matrices.md
    - RXMeshDynamic: rxmesh/dynamic.md    
    - Autodiff: rxmesh/ad.md
    - Applications: rxmesh/apps.md
  - References: 
    - Handles: rxmesh/handles.md
    - Iterators: rxmesh/iterators.md
    - Logging: rxmesh/logging.md

